name: ganastro
channels:
  - pytorch
  - bioconda
  - nvidia
  - anaconda
  - astropy
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=1.4.0
  - alembic=1.8.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - args=0.1.0
  - astropy=5.3.4
  - astropy-iers-data=0.2024.3.18.0.29.47
  - astroquery=0.4.6
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - clint=0.5.1
  - colorama=0.4.6
  - colorlog=5.0.1
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dace-query=1.1.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.5.0
  - fastdtw=0.2.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gdown=5.1.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=3.0.1
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - hdf5=1.12.1
  - html5lib=1.1
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.1.2
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.0.20
  - libcups=2.4.2
  - libcurand=10.3.5.119
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lightning-utilities=0.9.0
  - llvm-openmp=14.0.6
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numba=0.59.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - optuna=3.6.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyamg=4.2.3
  - pycparser=2.21
  - pyerfa=2.0.0
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyvo=1.5.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn=1.2.2
  - scipy=1.12.0
  - seaborn=0.12.2
  - secretstorage=3.3.1
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - torchaudio=2.2.1
  - torchinfo=1.8.0
  - torchmetrics=1.4.0.post0
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.7.1
  - tslearn=0.6.3
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.3.8
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.31.0
    - annotated-types==0.7.0
    - antropy==0.1.6
    - appdirs==1.4.4
    - astunparse==1.6.3
    - beartype==0.18.5
    - bidict==0.23.1
    - cachetools==5.3.3
    - click==8.1.7
    - cloudpickle==3.0.0
    - deepspeed==0.14.3
    - denoising-diffusion-pytorch==2.0.6
    - dm-tree==0.1.8
    - dtaidistance==2.3.11
    - einops==0.8.0
    - ema-pytorch==0.5.0
    - flatbuffers==24.3.25
    - flwr==1.9.0
    - frozendict==2.4.4
    - fsspec==2024.5.0
    - gast==0.5.4
    - google-auth==2.29.0
    - google-auth-oauthlib==1.2.0
    - google-pasta==0.2.0
    - grpcio==1.64.1
    - h5py==3.11.0
    - hjson==3.1.0
    - huggingface-hub==0.23.3
    - iterators==0.0.2
    - libclang==18.1.1
    - lxml==5.2.2
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - ml-dtypes==0.3.2
    - multitasking==0.0.11
    - ninja==1.11.1.1
    - nvidia-ml-py==12.555.43
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pathspec==0.12.1
    - patsy==0.5.6
    - prettytable==3.10.0
    - protobuf==4.25.3
    - py-cpuinfo==9.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pyastronomy==0.21.0
    - pycryptodome==3.20.0
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pytorch-fid==0.3.0
    - quantities==0.15.0
    - requests-oauthlib==2.0.0
    - rich==13.7.1
    - rsa==4.9
    - safetensors==0.4.3
    - shellingham==1.5.4
    - spectrum-overload==0.3
    - statsmodels==0.14.2
    - stochastic==0.6.0
    - tbparse==0.0.8
    - termcolor==2.4.0
    - tomli==2.0.1
    - typer==0.9.4
    - wget==3.2
    - wrapt==1.14.1
    - yfinance==0.2.28
